- hosts: all
  tasks:
#     - name: stop container
#       shell: docker container stop maven-assignment
#     - name: remove container
#       shell: docker container rm maven-assignment
#     - name: remove docker image
#       shell: docker image rm imajeetyadav/maven-assignment
    - name: create new container
      shell: docker container run -itd --name maven-assignment -p 8080:8080 imajeetyadav/maven-assignment
